"""Create contacts table

Revision ID: 066cb4ca712a
Revises: ac5e52cdfa6e
Create Date: 2024-10-02 18:04:25.119799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066cb4ca712a'
down_revision = 'ac5e52cdfa6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=36), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Contacts')
    # ### end Alembic commands ###
