"""added new field

Revision ID: 20801c48edea
Revises: 4af6427847ac
Create Date: 2024-10-02 17:19:29.763654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20801c48edea'
down_revision = '4af6427847ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_released', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.drop_column('is_released')

    # ### end Alembic commands ###
