"""Create stuntmen table

Revision ID: 4af6427847ac
Revises: b7b1a0454bb0
Create Date: 2024-10-01 18:52:12.342267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af6427847ac'
down_revision = 'b7b1a0454bb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stuntmen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('cast_in_films', schema=None) as batch_op:
        batch_op.alter_column('film_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('actor_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cast_in_films', schema=None) as batch_op:
        batch_op.alter_column('actor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('film_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('stuntmen')
    # ### end Alembic commands ###
