"""rename phone_number to social_media

Revision ID: dfc7d3f34725
Revises: 066cb4ca712a
Create Date: 2024-10-02 19:56:45.507384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfc7d3f34725'
down_revision = '066cb4ca712a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publicist_agent_info', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('social_media', sa.String(length=128), nullable=True))
        batch_op.drop_column('phone_number')
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=36), nullable=True))
        batch_op.drop_column('social_media')
        batch_op.drop_column('publicist_agent_info')

    # ### end Alembic commands ###
